import React from 'react';
import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import '../globals.css';

export const metadata: Metadata = {
	title: 'Threads',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<ClerkProvider
				appearance={{
					baseTheme: dark,
				}}
			>
				<body className='bg-dark-1'>{children}</body>
			</ClerkProvider>
		</html>
	);
}
